server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# 数据库配置
database:
  default:
  - link: "mysql:root:@tcp(127.0.0.1:3306)/liteflow"
    debug: true
    charset: "utf8mb4"
    maxIdle: 10
    maxOpen: 100
    maxLifetime: "30s"

logger:
  level : "all"
  stdout: true