// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package liteflow

import (
	"go-liteflow-editor-client/api/liteflow"
)

type ControllerV1 struct{}

func NewV1() liteflow.ILiteflowV1 {
	return &ControllerV1{}
}
