// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-liteflow-editor-client/internal/dao/internal"
)

// liteflowScriptDao is the data access object for the table liteflow_script.
// You can define custom methods on it to extend its functionality as needed.
type liteflowScriptDao struct {
	*internal.LiteflowScriptDao
}

var (
	// LiteflowScript is a globally accessible object for table liteflow_script operations.
	LiteflowScript = liteflowScriptDao{internal.NewLiteflowScriptDao()}
)

// Add your custom methods and functionality below.
