// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-liteflow-editor-client/internal/dao/internal"
)

// liteflowLogDao is the data access object for the table liteflow_log.
// You can define custom methods on it to extend its functionality as needed.
type liteflowLogDao struct {
	*internal.LiteflowLogDao
}

var (
	// LiteflowLog is a globally accessible object for table liteflow_log operations.
	LiteflowLog = liteflowLogDao{internal.NewLiteflowLogDao()}
)

// Add your custom methods and functionality below.
