// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-liteflow-editor-client/internal/dao/internal"
)

// liteflowNodeDao is the data access object for the table liteflow_node.
// You can define custom methods on it to extend its functionality as needed.
type liteflowNodeDao struct {
	*internal.LiteflowNodeDao
}

var (
	// LiteflowNode is a globally accessible object for table liteflow_node operations.
	LiteflowNode = liteflowNodeDao{internal.NewLiteflowNodeDao()}
)

// Add your custom methods and functionality below.
