// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-liteflow-editor-client/internal/dao/internal"
)

// liteflowChainDao is the data access object for the table liteflow_chain.
// You can define custom methods on it to extend its functionality as needed.
type liteflowChainDao struct {
	*internal.LiteflowChainDao
}

var (
	// LiteflowChain is a globally accessible object for table liteflow_chain operations.
	LiteflowChain = liteflowChainDao{internal.NewLiteflowChainDao()}
)

// Add your custom methods and functionality below.
